name: .github/workflows/flutter-ci.yml

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'libs/**'
      - 'flutter/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/**'

jobs:
  build-windows:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "nightly"
